CONTIKI_PROJECT = udp-client udp-server
all: $(CONTIKI_PROJECT)

MODULES += os/services/shell

TARGET = simplelink
BOARD = launchpad/cc1310
DEBUG = 1

CONTIKI=../..
include $(CONTIKI)/Makefile.include
